### ISSUE TITLE
DOI / Subscription at order success

### ISSUE THREAD

**Issue by Elfen-Service** [Turiknox/magento-checkout-newsletter#2]
At the moment the DOI / subscription is done when saving the billing address.
So if a customer goes back to change something or similar the customer maybe would get multiple mails.
It would be better to move this to the success event.

**Comment by scottaparsons** [comment]
Hello.

Thanks for letting me know.

From what I can remember, the form data from the billing address section cannot be accessed from the success event. Having said that, I have added in functionality to stop multiple confirmation emails from being sent to the customer.
